### ISSUE TITLE
MMweb/source/index.html.md

### ISSUE THREAD

**Issue by instructian** [CSUEBMMG/MMweb#1]
video link does not seem to update?

**Comment by philiptzou** [comment]
I saw you solved the issue by yourself?

**Comment by instructian** [comment]
no - the slipstream video is still show but it should be the intro video

On Sat, Feb 6, 2016 at 1:05 PM, Philip Tzou <notifications@github.com>
wrote:

> I saw you solved the issue by yourself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSUEBMMG/MMweb/issues/1#issuecomment-180863763>.
>



-- 

-- 
*kicking the beehive since 1966*
*Ian Pollock*
Assistant Professor
Multimedia Graduate Program
Multimedia Program Coordinator

Department of Art
School of Arts and Media
California State University East Bay



<http://www.guerrillagrafters.org/> 540 Alabama Street #303
San Francisco, California 94110 US
Mobile: 415-522-0605
Office: 510-885-2427

instructian@gmail.com

portfolio: http://instructian.com
mapping hate - biasmap.org
<http://www.biasmap.org/>being uncivilized - guerrillagrafters.org
<http://www.guerrillagrafters.org/>

Facebook.com/ianpollock
twitter.com/#!/instructian
http://www.linkedin.com/in/ianpollock
ianppollock (Skype)


<http://www.linkedin.com/e/sig/11340928/?hs=false&tok=3N29vSEgsv05g1>

**Comment by instructian** [comment]
how do we fix the video so that we can change it easily?

**Comment by philiptzou** [comment]
Well, the video changed here: http://csuebmmg.github.io/MMweb/

The problem in multimedia.csueastbay.edu is because the SSH access is revoked. Unfortunately the tool used to deploy code to the production server is rsync, which based on SSH access.

**Comment by MultimediaGraduateProgram** [comment]
oh ok - so how are we updating at this time?


On Tue, Feb 9, 2016 at 5:39 PM, Philip Tzou <notifications@github.com>
wrote:

> Well, the video changed here: http://csuebmmg.github.io/MMweb/
>
> The problem in multimedia.csueastbay.edu is because the SSH access is
> revoked. Unfortunately the tool used to deploy code to the production
> server is rsync, which based on SSH access.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSUEBMMG/MMweb/issues/1#issuecomment-182162237>.
>



-- 


*kicking the beehive and making stuff *
*Ian Pollock*
Assistant Professor
Graduate and Undergraduate Multimedia Studies Coordinator

Department of Art
School of Arts and Media
California State University East Bay
25800 Carlos Bee Boulevard
Hayward, CA 94542
ian.pollock@csueastbay.edu
510-885-2427
  meeting: http://doodle.com/ianpollock
advising hours: Tue/Thu 12noon - 2pm
web: multimedia.csueastbay.edu

NOTICE:
This message, including attachments, is intended only for the designated
recipient(s). It may contain confidential or proprietary information and
may be subject to the attorney-client privilege or other confidentiality
protections. If the reader of this message is not the intended recipient,
or an authorized employee or agent of the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited and may subject you to civil action
and/or criminal prosecution. If you have received this communication in
error, please notify us by replying to this message and deleting it from
your computer and any network to which your computer is connected. Thank
you.

**Comment by instructian** [comment]
so how often does it revoke? what do we need to do?

**Comment by instructian** [comment]
do i generate a new key?

**Comment by philiptzou** [comment]
No you don't generate a new key... just grant ssh access again.

Or if it's not emergency we can wait until Travis CI merge this pull request:

https://github.com/travis-ci/apt-package-whitelist/pull/2403

Then we can use [these steps](http://serverfault.com/questions/135618/is-it-possible-to-use-rsync-over-sftp-without-an-ssh-shell/313382#313382) to deploy code without ssh access.

**Comment by philiptzou** [comment]
Resolved.
