### ISSUE TITLE
social media icons

### ISSUE THREAD

**Issue by instructian** [csuebmmg/MMweb#5]
i am not sure that i understand how the sprites are being generated and then displayed.  i thought i added them to all the right places?

**Comment by MultimediaGraduateProgram** [comment]
nevermind - it did not work locally but it's picking up the changes on line

ian wrote:

**Comment by instructian** [comment]
I just pulled the repo to update and i am getting this error 

/Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_helpers.scss:2: Undefined variable: "$icons". (Sass::SyntaxError)
  (in /Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_main.scss:2)
	from /Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_main.scss:17
