### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by instructian** [csuebmmg/MMweb#7]
The command "openssl aes-256-cbc -K $(eval echo \$encrypted_$(eval echo \${REPO_ID_${OWNER_NAME}})_key) -iv $(eval echo \$encrypted_$(eval echo \${REPO_ID_${OWNER_NAME}})_iv) -in .travis/${OWNER_NAME}.pem.enc -out .travis/${OWNER_NAME}.pem -d" failed and exited with 1 during .

I tried rolling it back to the last successful build and still there is an error.  do you have any ideas of how to fix this? @philiptzou

**Comment by instructian** [comment]
@philiptzou do you have any idea of how i would reset this properly?  or is the error related to something else?

**Comment by philiptzou** [comment]
No but I'll take a look soon.

**Comment by philiptzou** [comment]
Fixed. Was it you who changed the group name from "CSUEBMMG" to "csuebmmg"?
