### ISSUE TITLE
Broken $icons variable?

### ISSUE THREAD

**Issue by instructian** [csuebmmg/MMweb#8]
/Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_helpers.scss:2: Undefined variable: "$icons". (Sass::SyntaxError)
  (in /Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_main.scss:2)
	from /Users/ian/Documents/01-GITHUBREPOS/MMweb/source/stylesheets/_main.scss:17

**Comment by philiptzou** [comment]
Fixed at https://github.com/csuebmmg/MMweb/commit/c519d9693fa51ee8e9e55b0217b104317cfaabdc.
