### ISSUE TITLE
recruiterbox api changed

### ISSUE THREAD

**Issue by instructian** [csuebmmg/MMweb#9]
Looks like they changed the recruiterbox api http://multimedia.csueastbay.edu/apply/#op-119239-masters-degree-in-multimedia

it no longer finds the jobs https://csuebmultimedia.recruiterbox.com/jobs/fk0marz

they have some new documentation here https://github.com/Recruiterbox and here https://developers.recruiterbox.com/

**Comment by philiptzou** [comment]
I need to see the content in Widget (copy/paste) but it asked me to login.

**Comment by instructian** [comment]
I am using the new link - you have an account at recruiterbox now - it would be great to get rid of the two step process  like we had it before
